---
title: "About"
---


:::{#hero-heading}

:::

## In a nutshell

I am research scientist and Associate Professor with a specialization in the cognitive mechanisms underlying memory, attention, and decision making. I focus primarily on studying the variables that influence how people remember (or forget) to fulfill everyday intentions at the home, at school, or in the workplace. My recent work has focused on how financial gains or losses can influence memory for carrying out such tasks, which may have implications for workplace performance and bonus structures. I also study how people remember the origin of information, which plays a role in distinguishing between reality and imagination as well as attributing ideas to team members accurately.

## Hobbies & Other Interests

I enjoy a simple, minimalist lifestyle and the flexibility that comes with that freedom. I love deep conversation with anyone who is willing to share his or her views about reality and fantasy or anywhere between. In my spare time, I like to boulder at the gym with my wife, tend to our garden and preserve our bounty, cycle, and ferment foods.

I am a fan of efficiency, automation, and work flow. In my spare time, I enjoy writing scripts and programs that automate either annoying or repetitive tasks for myself or for others. I believe there is more to life than doing manually what computers can do more accurately and efficiently.
